# Use container-based infrastructure
sudo: false

language: scala

# These directories are cached to S3 at the end of the build
cache:
    directories:
        - $HOME/.ivy2/cache
        - $HOME/.sbt/boot/

scala:
    - 2.12.12
    - 2.13.3

jdk:
  - openjdk8

env:
    # This splits the build into n parts
    matrix:
        - TEST_COMMAND="integration/test"

script:
    - sbt ++2.12.12! -J-XX:ReservedCodeCacheSize=256M "scalaxbPlugin/scripted"
    - sbt ++$TRAVIS_SCALA_VERSION! -J-XX:ReservedCodeCacheSize=256M "$TEST_COMMAND"
    # Tricks to avoid unnecessary cache updates
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
